---
title: "Shape portrait cantonaux"
author: "Duc-Quang Nguyen"
date: "3 February 2017"
output: html_document
---

```{r setup, include=FALSE}
xls.file <- "je-f-21.03.02-2.xls"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(readxl)
```

```{r load xls}
xls.read <- read_excel(xls.file, skip = 1)

# discard NA rows
na.row <- apply(xls.read, 1, function(l) all(is.na(l)))
xls.read <- xls.read[!na.row,]

# find table end, starts with '1) Selon la typologie '
na.from <- grep("1) Selon la typologie", unlist(xls.read[,1]), fixed = T)
xls.read <- xls.read[-(na.from:nrow(xls.read)),]

# Find the rows that are titles for subsequent rows (i.e. NA rows except first column)
na.row <- apply(xls.read, 1, function(l) all(is.na(l[-1])))
xls.read <- xls.read[!na.row,]

# relabel columsn and drop Suisse and year of data
colnames(xls.read) <- xls.read[1,]
colnames(xls.read)[1] <- 'indicator'
xls.read <- xls.read[-1,]
xls.read %<>% select(-`Années`, -Suisse)

# Find the rows that are titles for subsequent rows (i.e. NA rows except first column)
na.row <- apply(xls.read, 1, function(l) all(is.na(l[-1])))
xls.read <- xls.read[!na.row,]
# drop the rows showing the % difference between 2 time perids
xls.read %<>% filter(!grepl('Variation en %', indicator))

# drop some absolute indicators
xls.read %<>% filter(!grepl('(Part des surfaces bio dans la surface agricole utile totale en %|Etablissements, total|Taux de logements occupés par leur propriétaire 2)|Arrivées dans les hôtels et établissements de cure en milliers|Nuitées dans les hôtels et établissements de cure en milliers|Secteur primaire|Secteur secondaire|Secteur tertiaire|Emplois, total en milliers|Etablissements, total)', indicator, fixed = T))

xls.read %<>% filter(!grepl('(Emplois, total en milliers|Secteur primaire|Secteur secondaire|Secteur tertiaire|Part des surfaces bio dans la surface agricole utile totale en %|Etablissements, total|Taux de logements occupés par leur propriétaire 2)|Arrivées dans les hôtels et établissements de cure en milliers|Nuitées dans les hôtels et établissements de cure en milliers|Etablissements, total)', indicator))

# rename some columns
xls.read$indicator[grep("par km²", xls.read$indicator)] <- 'Population par km2'
xls.read$indicator[grep("^selon", xls.read$indicator)] <- paste0("Infractions en % de la population totale", xls.read$indicator[grep("^selon", xls.read$indicator)])
# remove suffix number
xls.read$indicator[grep("\\d\\)", xls.read$indicator, perl = T)] <- gsub(" \\d\\)", "", xls.read$indicator[grep("\\d\\)", xls.read$indicator, perl = T)])


# make the data long
df <- apply(t(xls.read[,-1]), 2, function(cl)  as.numeric(gsub("\\((.*)\\)", "\\1", cl)))
colnames(df) <- unlist(xls.read[,1], use.names = F)
rownames(df) <- colnames(xls.read[,-1])

```